// constants/barangays.ts
// Shared barangay list for Davao City — used by both profile.tsx and profile.web.tsx

export const BARANGAY_OPTIONS: string[] = [
    'Barangay 1-A','Barangay 2-A','Barangay 3-A','Barangay 4-A','Barangay 5-A',
    'Barangay 6-A','Barangay 7-A','Barangay 8-A','Barangay 9-A','Barangay 10-A',
    'Barangay 11-B','Barangay 12-B','Barangay 13-B','Barangay 14-B','Barangay 15-B',
    'Barangay 16-B','Barangay 17-B','Barangay 18-B','Barangay 19-B','Barangay 20-B',
    'Barangay 21-C','Barangay 22-C','Barangay 23-C','Barangay 24-C','Barangay 25-C',
    'Barangay 26-C','Barangay 27-C','Barangay 28-C','Barangay 29-C','Barangay 30-C',
    'Barangay 31-D','Barangay 32-D','Barangay 33-D','Barangay 34-D','Barangay 35-D',
    'Barangay 36-D','Barangay 37-D','Barangay 38-D','Barangay 39-D','Barangay 40-D',
    'Bago Aplaya','Bago Gallera','Baliok','Bucana (76-A)','Catalunan Grande',
    'Catalunan Pequeño','Dumoy','Langub','Ma-a','Magtuod','Matina Aplaya',
    'Matina Crossing (74-A)','Matina Pangi','Talomo Proper','Agdao Proper',
    'Centro (San Juan)','Gov. Paciano Bangoy','Gov. Vicente Duterte',
    'Kap. Tomas Monteverde, Sr.','Lapu-Lapu','Leon Garcia','Rafael Castillo',
    'San Antonio','Ubalde','Wilfredo Aquino','Acacia','Alfonso Angliongto Sr.',
    'Buhangin Proper','Cabantian','Callawa','Communal','Indangan','Mandug',
    'Pampanga','Sasa','Tigatto','Vicente Hizon Sr.','Waan',
    'Alejandra Navarro (Lasang)','Bunawan Proper','Gatungan','Ilang','Mahayag',
    'Mudiang','Panacan','San Isidro (Licanan)','Tibungco','Colosas',
    'Fatima (Benowang)','Lumiad','Mabuhay','Malabog','Mapula','Panalum',
    'Pandaitan','Paquibato Proper','Paradise Embak','Salapawan','Sumimao',
    'Tapak','Baguio Proper','Cadalian','Carmen','Gumalang','Malagos',
    'Tambobong','Tawan-Tawan','Wines','Biao Joaquin','Calinan Proper',
    'Cawayan','Dacudao','Dalagdag','Dominga','Inayangan','Lacson','Lamanan',
    'Lampianao','Megkawayan','Pangyan','Riverside','Saloy','Sirib','Subasta',
    'Talomo River','Tamayong','Wangan','Baganihan','Bantol','Buda','Dalag',
    'Datu Salumay','Gumitan','Magsaysay','Malamba','Marilog Proper','Salaysay',
    'Suawan (Tuli)','Tamugan','Alambre','Atan-Awe','Bangkas Heights',
    'Baracatan','Bato','Bayabas','Binugao','Camansi','Catigan',
    'Crossing Bayabas','Daliao','Daliaon Plantation','Eden','Kilate','Lizada',
    'Lubogan','Marapangi','Mulig','Sibulan','Sirawan','Tagluno','Tagurano',
    'Tibuloy','Toril Proper','Tungkalan','Angalan','Bago Oshiro',
    'Balenggaeng','Biao Escuela','Biao Guinga','Los Amigos','Manambulan',
    'Manuel Guianga','Matina Biao','Mintal','New Carmen','New Valencia',
    'Santo Niño','Tacunan','Tagakpan','Talandang','Tugbok Proper','Ula',
];